### ISSUE TITLE
GPU info not correctly displayed.

### ISSUE THREAD

**Issue by TimHe95** [scar45/conky_solar_burn#6]
![image](https://user-images.githubusercontent.com/18543932/111473199-bf8bf800-8765-11eb-9e6e-2d0e6e9f4189.png)  
I have installed the driver:  
![image](https://user-images.githubusercontent.com/18543932/111473277-d4688b80-8765-11eb-9602-f0156f34ff58.png)

**Comment by scar45** [comment]
This could be one of two things. First, ensure that the Conky variables in `.conkyrc` are of the following:
```
${nvidia temp}
${nvidia gpufreq}
${nvidia memfreq}
```
...as it looks like you might only have `${nvidia}` there. 

If `.conkyrc` looks correct however, then it's possible that the version of Conky you're using was not compiled with the references to nvidia. You can verify this by running `conky -V`, and within the output, if nvidia is supported, you should see it listed:
```
conky 1.11.7_pre compiled 2021-01-04 for Linux x86_64

Compiled in features:
...
* wireless
* support for IBM/Lenovo notebooks
* nvidia <----
* builtin default configuration
...
```
If you don't see it listed, you'll need to check with your distro package manager for a potential `conky-nvidia` package, or obtain it elsewhere. Hope that helps.
