### ISSUE TITLE
amd gpu support

### ISSUE THREAD

**Issue by ghost** [scar45/conky_solar_burn#7]
hello, first of all, I absolutely adore your theme. it is simple and beautiful. thank you for your work!

is it possible to also track an AMD GPU with it?

thank you

**Comment by scar45** [comment]
Thanks for the kind words @seether5! Glad you are enjoying it.

I don't have an AMD GPU myself, but I did find [**this post**](https://forum.level1techs.com/t/how-i-got-conky-to-show-my-amdgpu-temps-and-amd-cpu-temps/138753) which basically describes how you can use `radeontop` to get data, then `grep` and `cut` the result to extract the info you need.

Hopefully that helps!

**Comment by ghost** [comment]
oh yeah i will look into that. cheers
